api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    eager_loading:
        enabled: true
    collection:
        pagination:
#            enabled: false
#            client_enabled: true
#            enabled_parameter_name: pagination
            page_parameter_name: sayfa
            items_per_page: 5
            client_items_per_page: true #default is false
            items_per_page_parameter_name: adet
            maximum_items_per_page: 10
            partial: false
            client_partial: true
            partial_parameter_name: partial
    exception_to_status:
        App\Exception\EmptyBodyException: 400
        App\Exception\InvalidConfirmationTokenException: 404
